### ISSUE TITLE
求添加UOS协议登陆

### ISSUE THREAD

**Issue by IlineI** [chenls/weixin-watch#1]
我添加了还是提示E/WxLogin: cookiesToStr: cookies is null
GitHub的wechrome项目里有UOS协议的值
需要在登陆时修改header添加两个值
分别是
"client-version", "2.0.0",
"extspam", "Gr8GCLkGErkGCggwMDAwMDAwMRAGGqAGzGkdmsypKcqwZ6eZkyquH8GMqK4TQ0wtkHFH1iVJhLeKKb5HLu+E25f/ivHzxf6H56j0as31NM0DmpH9hPxFvAIbtTdHmNj3J0QN4+bAQDn8PJmOoHHdfQrqGgbx8WA+Mt4JIop+q0dAiS7GOkFFMkOEeEXXgNkuAWMvX4N489/xiiO30il7RVwtINU4rgpyH7cVcf6KW1EB7yiDpHW18Q/wSyMPU7NATmSDePKDbvuMv8yVeXZEfb/K6QsYB+JvUdNl/99ODXXC20I+T34HHmW25aPK+XZ5nFlLorhN63zgoLyE3JWYZb0iDWjo7iYf2rsV5H6+SolqMDTy8AIzPju/gdGp4d9imRZS3m+Y09OfO8HCHso2dugPaqNiKatxU5w53AP857VVAEOZR0sEE+S9b6YZhE0zM01MGk7MZaNoEjEovoPA4VbvGSVM/g7t4ZbF07prmkNUi8K0IFlPktm9jj2eimC5rai8E4mfCBBHexzB5Dri19y+EUhQwYcOStBoWKmS8mNgWGKL+mFoyK/lw5+X3NLoO/0RoJjRFKxp3y2g4Ji7+vg0J7OhNlxbdxHwz76xXlT0WOpPFvP/yBN8cY7ohlo9UrBxsTx8D4ogYUud0/vvkHWOnJOoM1oe+PcwYVdopT1UpwyzS3BkS956ZZQTVfiYWSJ8N/x0JjymzAAm6tR2d0+ceH4Jy0GFoXXemWiZXMHylTnvLzF0Emw03NMnyJQ9tfAdjWogJ0eBK++1zMSrYR/9Qe9Sie+ENcESNvgEEdg/A1nH3pN7Aq8UPNzkG5ol0sUfQcck+zqgTcCAEVzeAwvcNv1PQSgpppjWQHBzwy8RwOzI5/I+9Tb17Os78yG6rrAN0utbsH8za8RMCSL2wChgZHth31Cdgi/5V++VTl/ikO3JMyaQYpox8EYoF94+CgkXjgoa2mz5sq4rQQFGpBg7tvR1ZhM30KACXl3QaydiIEKCXDLqarjNixqDwIwrEwB77yvz9CNA9JWr7U1tKlh94bbZUvDtFHTf03myUygi/UEODTZ3BQ28cnqN+pPMqTymGhzrvmwgrdjWhQYoBTAA";

**Comment by chenls** [comment]
您好！您的来信已收悉，我将尽快处理！谢谢！
